#!/usr/bin/env bash

get_chunk() {
    sed -n "/\`\`\`${1}/,/\`\`\`/p" | sed '1d;$d'
}

join_lines_remove_spaces() {
    tr '\n' ' ' | sed 's/ //g'
}

min_css() {
    sed 's/^ *//g;/margin:/s/ /_/g' | join_lines_remove_spaces | tr _ ' '
}

min_js() {
    sed 's/\/\/.*$//' | join_lines_remove_spaces | sed 's/letx/let x/'
}

min_html() {
    grep -v '<!--'
}

print_output() {
    local css="$(cat README.md | get_chunk css | min_css)"
    local html="$(cat README.md | get_chunk html | min_html)"
    local js="$(cat README.md | get_chunk javascript | min_js)"

    printf %s "<!DOCTYPE html><style>$css</style>$html<script>$js</script>"
}

print_output > index.html
